services:
  auth-service:
    build: ./back-end/auth-service
    container_name: auth-fumi
#    ports:
#      - "8080:8080"
    expose:
      - 8080
    env_file:
      - ./back-end/auth-service/.env
    networks:
      - private
      - fumi-network
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-fumi
#    ports:
#      - "15672:15672"
    expose:
      - 15672
      - 5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - private

  lambda-bridge:
    build: ./back-end/python-bridge-lambda
    container_name: lambda-bridge-fumi
    env_file:
      - ./back-end/python-bridge-lambda/.env
    depends_on:
      - rabbitmq
    restart: on-failure
    networks:
      - private
  
  db:
    image: postgres:15-alpine
    container_name: db-fumi
    restart: always
#    ports:
#      - "5433:5432"
    expose:
      - 5432
    networks:
      - private
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  products-service:
    build: ./back-end/products-service
    container_name: products-fumi
#    ports:
#      - "8081:8080"
    expose:
      - 8080
    env_file:
      - ./back-end/products-service/.env
    networks:
      - private
      - fumi-network
    depends_on:
      db:
        condition: service_healthy
      
  user-related-service:
    build: ./back-end/user-related-service
    container_name: user-fumi
#    ports:
#      - "8082:8080"
    expose:
      - 8080
    env_file:
      - ./back-end/user-related-service/.env
    networks:
      - private
      - fumi-network
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      auth-service:
        condition: service_started

  cart-service:
    build: ./back-end/cart-service
    container_name: cart-fumi
#    ports:
#      - "8083:8080"
    expose:
      - 8080
    env_file:
      - ./back-end/cart-service/.env
    networks:
      - private
      - fumi-network
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      auth-service:
        condition: service_started
      products-service:
        condition: service_started
      
  redis:
    image: redis:7-alpine
    container_name: redis-fumi
#    ports:
#      - "6379:6379"
    expose:
      - 6379
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    networks:
      - private

  frontend:
    build: ./front-end
    container_name: frontend-fumi
#    ports:
#      - "3000:80"
    expose:
      - 80
    networks:
      - private
      - public
      - fumi-network
    env_file:
      - ./front-end/.env
    restart: on-failure
    depends_on:
      - auth-service
      - products-service
      - user-related-service
      - cart-service


networks:
  private:
    driver: bridge
  public:
    driver: bridge
  fumi-network:
    external: true

volumes:
  pgdata:
  redis_data:
