services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    env_file:
      - ./auth-service/.env
    networks:
      - private
    restart: on-failure
    depends_on:
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - private

  lambda-bridge:
    build: ./python-bridge-lambda
    container_name: lambda-bridge
    env_file:
      - ./python-bridge-lambda/.env
    depends_on:
      - rabbitmq
    restart: on-failure
    networks:
      - private
  
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5432"
    networks:
      - private
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  products-service:
    build: ./products-service
    ports:
      - "8081:8080"
    env_file:
      - ./products-service/.env
    networks:
      - private
    depends_on:
      - db
      
  user-related-service:
    build: ./user-related-service
    ports:
      - "8082:8080"
    env_file:
      - ./user-related-service/.env
    networks:
      - private
    restart: on-failure
    depends_on:
      - db
      - redis
      - rabbitmq

  cart-service:
    build: ./cart-service
    ports:
      - "8083:8080"
    env_file:
      - ./cart-service/.env
    networks:
      - private
    restart: on-failure
    depends_on:
      - db
      
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    networks:
      - private


networks:
  private:
    driver: bridge

volumes:
  pgdata:
  redis_data:

